name: Delete infrastructure with Terraform
on:
  workflow_dispatch:
env:
      access_key: "${{secrets.YC_ACCESS_KEY}}"
      secret_key: "${{secrets.YC_SECRET_KEY}}"
      oauth: "${{secrets.YC_OAUTH}}"
      cloud: "${{secrets.YC_CLOUD}}"
      folder: "${{secrets.YC_FOLDER}}"
      ssh_private: "${{ secrets.SSH_PRIVATE_KEY }}"
      ssh_public: "${{ secrets.SSH_PUBLUC_KEY }}"      
#defaults:
#  run:
#    working-directory: ../yandex-cloud-terraform
jobs:
  terraform:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ../yandex-cloud-terraform    
    steps:
    
      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{env.ssh_private }}" > ~/.ssh/id_rsa
          install -m 600 -D /dev/null ~/.ssh/id_rsa.pub
          echo "${{env.ssh_public }}" > ~/.ssh/id_rsa.pub
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: insert baket keys
        run: |
          cd yandex-cloud-terraform
          echo '  access_key = "${{env.access_key }}"'  >> backend.tfbackend 
          echo '  secret_key = "${{env.secret_key }}"'  >> backend.tfbackend
                 
      - name: create locals file
        run: |
          cd yandex-cloud-terraform
          echo 'locals {' > locals.tf
          echo '  oauth  = "${{env.oauth }}"'  >> locals.tf 
          echo '  cloud  = "${{env.cloud }}"'  >> locals.tf 
          echo '  folder = "${{env.folder }}"'  >> locals.tf 
          echo '}'  >> locals.tf
          cat locals.tf
          
      - name: init Terraform
        run: |
          cd yandex-cloud-terraform
          terraform init -backend-config=backend.tfbackend
          
      - name: destroy Terraform
        run: |
          cd yandex-cloud-terraform
          terraform destroy  --auto-approve
