name: Deploy infrastructure with Terraform
on:
  workflow_dispatch:
env:
      access_key: "${{secrets.YC_ACCESS_KEY}}"
      secret_key: "${{secrets.YC_SECRET_KEY}}"
      oauth: "${{secrets.YC_OAUTH}}"
      cloud: "${{secrets.YC_CLOUD}}"
      folder: "${{secrets.YC_FOLDER}}"
      secrets: "${{secrets.YC_ACCESS_KEY}}"
#defaults:
#  run:
#    working-directory: ../yandex-cloud-terraform
jobs:
  terraform:
    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ../yandex-cloud-terraform    
    steps:
    
      - name: Install SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          install -m 600 -D /dev/null ~/.ssh/id_rsa.pub
          echo "${{ secrets.SSH_PUBLUC_KEY }}" > ~/.ssh/id_rsa.pub
          
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1

      - name: insert baket keys
        run: |
          cd yandex-cloud-terraform
          echo '  access_key = "${{ access_key }}"'  >> backend.tfbackend 
          echo '  secret_key = "${{ secret_key }}"'  >> backend.tfbackend
          
      - name: create locals file
        run: |
          cd yandex-cloud-terraform
          echo "locals {" > locals.tf
          echo '  oauth  = "${{ oauth }}"'  >> locals.tf 
          echo '  cloud  = "${{ cloud }}"'  >> locals.tf 
          echo '  folder = "${{ folder }}"'  >> locals.tf 
          echo '}'  >> locals.tf
          cat locals.tf
          
      - name: check format Terraform
        run: |
          cd yandex-cloud-terraform
          terraform fmt
        
      - name: init Terraform
        run: |
          cd yandex-cloud-terraform
          terraform init -backend-config=backend.tfbackend
        
      - name: validate Terraform
        run: |
          cd yandex-cloud-terraform
          terraform validate
          
      - name: plan Terraform
        run: |
          cd yandex-cloud-terraform
          terraform plan
      - name: apply Terraform
        run: |
          cd yandex-cloud-terraform
          terraform apply  --auto-approve
      
#      - name: run Ansible playbook
#        run: |
#          ls -aR
#          cp ./ops/ssh-config ~/.ssh/config
#          cat ~/.ssh/config
#          sudo apt update
#          sudo apt install software-properties-common
#          sudo add-apt-repository --yes --update ppa:ansible/ansible
#          sudo apt install ansible
#          ssh-agent bash
#          ansible-playbook -i ./playbooks/hosts.inv ./playbooks/playbook.yml
##        with:
##          auto_approve: true
        
#    - uses: hashicorp/terraform-github-actions/fmt@latest
#    - uses: hashicorp/terraform-github-actions/init@latest
#    - uses: hashicorp/terraform-github-actions/validate@latest
#    - uses: hashicorp/terraform-github-actions/plan@latest
#    - uses: hashicorp/terraform-github-actions/apply@latest
